apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-b0vk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-b0vk
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-b0vk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-b0vk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-b0vk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-masa-tenant/status-quarkus-io/statusquarkusio-b0vk@sha256:e1702de58ae79190fa09b624c8d8a77d789ec7eed29c5c41b6fc208cda5af6ba
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
